
POST http://localhost:8017/v1/products/ 
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MWNhN2YzNjI2Mjk5ZTI0NGRkZDQ1NjYiLCJpYXQiOjE2NDA2NzY0NjN9.8OGQvLdh5d9owKCQ38UZf4FBowMJLMZ7sH6Y9gBs_3c

{
    "title": "Test token 23",
    "price": 10,
    "images": ["https://media3.scdn.vn/img4/2020/12_10/YmrifeaFvW1L1zlwmWoI.jpg"],
    "quantites": 5,
    "description": "dsadsadsaadas"
}

###
// @register
POST http://localhost:8017/v1/register/ 
Content-Type: application/json

{
    "username": "lethanphuong2017",
    "password": "12345678"
}

###
// @login
POST http://localhost:8017/v1/login/ 
Content-Type: application/json

{
    "username": "lethanphuong2017",
    "password": "12345678"
}
